#############################################################################
# Makefile for building: sql
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Aug 13 11:01:43 2012
# Project:  sql.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile sql.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -Isearcher -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = constants.cpp \
		helpers.cpp \
		main.cpp \
		mainwindow.cpp \
		mytablemodel.cpp \
		switcher.cpp \
		searcher/catalog.cpp \
		searcher/filters.cpp \
		searcher/input.cpp \
		searcher/paramsselector.cpp \
		searcher/searcher.cpp \
		searcher/table.cpp moc_mainwindow.cpp \
		moc_mytablemodel.cpp \
		moc_switcher.cpp \
		moc_catalog.cpp \
		moc_input.cpp \
		moc_paramsselector.cpp \
		moc_searcher.cpp \
		moc_table.cpp \
		qrc_images.cpp
OBJECTS       = constants.o \
		helpers.o \
		main.o \
		mainwindow.o \
		mytablemodel.o \
		switcher.o \
		catalog.o \
		filters.o \
		input.o \
		paramsselector.o \
		searcher.o \
		table.o \
		moc_mainwindow.o \
		moc_mytablemodel.o \
		moc_switcher.o \
		moc_catalog.o \
		moc_input.o \
		moc_paramsselector.o \
		moc_searcher.o \
		moc_table.o \
		qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		sql.pro
QMAKE_TARGET  = sql
DESTDIR       = 
TARGET        = sql

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sql.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtSql.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile sql.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtSql.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile sql.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/sql1.0.0 || $(MKDIR) .tmp/sql1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sql1.0.0/ && $(COPY_FILE) --parents constants.h helpers.h mainwindow.h mytablemodel.h switcher.h searcher/catalog.h searcher/filters.h searcher/input.h searcher/paramsselector.h searcher/searcher.h searcher/table.h .tmp/sql1.0.0/ && $(COPY_FILE) --parents images.qrc .tmp/sql1.0.0/ && $(COPY_FILE) --parents constants.cpp helpers.cpp main.cpp mainwindow.cpp mytablemodel.cpp switcher.cpp searcher/catalog.cpp searcher/filters.cpp searcher/input.cpp searcher/paramsselector.cpp searcher/searcher.cpp searcher/table.cpp .tmp/sql1.0.0/ && (cd `dirname .tmp/sql1.0.0` && $(TAR) sql1.0.0.tar sql1.0.0 && $(COMPRESS) sql1.0.0.tar) && $(MOVE) `dirname .tmp/sql1.0.0`/sql1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sql1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_mytablemodel.cpp moc_switcher.cpp moc_catalog.cpp moc_input.cpp moc_paramsselector.cpp moc_searcher.cpp moc_table.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_mytablemodel.cpp moc_switcher.cpp moc_catalog.cpp moc_input.cpp moc_paramsselector.cpp moc_searcher.cpp moc_table.cpp
moc_mainwindow.cpp: searcher/searcher.h \
		searcher/filters.h \
		helpers.h \
		constants.h \
		switcher.h \
		searcher/catalog.h \
		searcher/table.h \
		mytablemodel.h \
		searcher/input.h \
		searcher/paramsselector.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_mytablemodel.cpp: mytablemodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mytablemodel.h -o moc_mytablemodel.cpp

moc_switcher.cpp: constants.h \
		switcher.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) switcher.h -o moc_switcher.cpp

moc_catalog.cpp: helpers.h \
		constants.h \
		searcher/catalog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/catalog.h -o moc_catalog.cpp

moc_input.cpp: constants.h \
		searcher/input.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/input.h -o moc_input.cpp

moc_paramsselector.cpp: constants.h \
		helpers.h \
		searcher/paramsselector.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/paramsselector.h -o moc_paramsselector.cpp

moc_searcher.cpp: searcher/filters.h \
		helpers.h \
		constants.h \
		switcher.h \
		searcher/catalog.h \
		searcher/table.h \
		mytablemodel.h \
		searcher/input.h \
		searcher/paramsselector.h \
		searcher/searcher.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/searcher.h -o moc_searcher.cpp

moc_table.cpp: helpers.h \
		constants.h \
		switcher.h \
		mytablemodel.h \
		searcher/table.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/table.h -o moc_table.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/first.png \
		images/last.png \
		images/prev.png \
		images/next.png
	/usr/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

constants.o: constants.cpp constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constants.o constants.cpp

helpers.o: helpers.cpp helpers.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpers.o helpers.cpp

main.o: main.cpp searcher/searcher.h \
		searcher/filters.h \
		helpers.h \
		constants.h \
		switcher.h \
		searcher/catalog.h \
		searcher/table.h \
		mytablemodel.h \
		searcher/input.h \
		searcher/paramsselector.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		searcher/searcher.h \
		searcher/filters.h \
		helpers.h \
		constants.h \
		switcher.h \
		searcher/catalog.h \
		searcher/table.h \
		mytablemodel.h \
		searcher/input.h \
		searcher/paramsselector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mytablemodel.o: mytablemodel.cpp mytablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mytablemodel.o mytablemodel.cpp

switcher.o: switcher.cpp switcher.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o switcher.o switcher.cpp

catalog.o: searcher/catalog.cpp searcher/catalog.h \
		helpers.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o catalog.o searcher/catalog.cpp

filters.o: searcher/filters.cpp searcher/filters.h \
		helpers.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filters.o searcher/filters.cpp

input.o: searcher/input.cpp searcher/input.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o input.o searcher/input.cpp

paramsselector.o: searcher/paramsselector.cpp searcher/paramsselector.h \
		constants.h \
		helpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paramsselector.o searcher/paramsselector.cpp

searcher.o: searcher/searcher.cpp searcher/searcher.h \
		searcher/filters.h \
		helpers.h \
		constants.h \
		switcher.h \
		searcher/catalog.h \
		searcher/table.h \
		mytablemodel.h \
		searcher/input.h \
		searcher/paramsselector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searcher.o searcher/searcher.cpp

table.o: searcher/table.cpp searcher/table.h \
		helpers.h \
		constants.h \
		switcher.h \
		mytablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o table.o searcher/table.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mytablemodel.o: moc_mytablemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mytablemodel.o moc_mytablemodel.cpp

moc_switcher.o: moc_switcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_switcher.o moc_switcher.cpp

moc_catalog.o: moc_catalog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_catalog.o moc_catalog.cpp

moc_input.o: moc_input.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_input.o moc_input.cpp

moc_paramsselector.o: moc_paramsselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_paramsselector.o moc_paramsselector.cpp

moc_searcher.o: moc_searcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searcher.o moc_searcher.cpp

moc_table.o: moc_table.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_table.o moc_table.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

