#############################################################################
# Makefile for building: sql
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Oct 24 14:26:08 2012
# Project:  sql.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile sql.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-32 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -Isearcher -I. -I.
LINK          = g++
LFLAGS        = -m32 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = basetable.cpp \
		constants.cpp \
		customcombobox.cpp \
		detailcard.cpp \
		helpers.cpp \
		main.cpp \
		mainwindow.cpp \
		mytablemodel.cpp \
		switcher.cpp \
		searcher/catalog.cpp \
		searcher/filters.cpp \
		searcher/greysearcher.cpp \
		searcher/greytable.cpp \
		searcher/input.cpp \
		searcher/paramsselector.cpp \
		searcher/searcher.cpp \
		searcher/whitesearcher.cpp \
		searcher/whitetable.cpp \
		settingsdialog.cpp \
		searcher/whiteadddialog.cpp \
		headercomboboxdelegate.cpp \
		customtabwidget.cpp \
		authorisewindow.cpp \
		searcher/greyadddialog.cpp \
		searcher/whitepriceseditor.cpp \
		changepricedatedialog.cpp \
		addyeardiscount.cpp \
		yearsdiscountsdialog.cpp moc_basetable.cpp \
		moc_customcombobox.cpp \
		moc_detailcard.cpp \
		moc_mainwindow.cpp \
		moc_mytablemodel.cpp \
		moc_switcher.cpp \
		moc_catalog.cpp \
		moc_greysearcher.cpp \
		moc_greytable.cpp \
		moc_input.cpp \
		moc_paramsselector.cpp \
		moc_searcher.cpp \
		moc_whitesearcher.cpp \
		moc_whitetable.cpp \
		moc_settingsdialog.cpp \
		moc_whiteadddialog.cpp \
		moc_headercomboboxdelegate.cpp \
		moc_customtabwidget.cpp \
		moc_authorisewindow.cpp \
		moc_greyadddialog.cpp \
		moc_whitepriceseditor.cpp \
		moc_changepricedatedialog.cpp \
		moc_addyeardiscount.cpp \
		moc_yearsdiscountsdialog.cpp \
		qrc_images.cpp
OBJECTS       = basetable.o \
		constants.o \
		customcombobox.o \
		detailcard.o \
		helpers.o \
		main.o \
		mainwindow.o \
		mytablemodel.o \
		switcher.o \
		catalog.o \
		filters.o \
		greysearcher.o \
		greytable.o \
		input.o \
		paramsselector.o \
		searcher.o \
		whitesearcher.o \
		whitetable.o \
		settingsdialog.o \
		whiteadddialog.o \
		headercomboboxdelegate.o \
		customtabwidget.o \
		authorisewindow.o \
		greyadddialog.o \
		whitepriceseditor.o \
		changepricedatedialog.o \
		addyeardiscount.o \
		yearsdiscountsdialog.o \
		moc_basetable.o \
		moc_customcombobox.o \
		moc_detailcard.o \
		moc_mainwindow.o \
		moc_mytablemodel.o \
		moc_switcher.o \
		moc_catalog.o \
		moc_greysearcher.o \
		moc_greytable.o \
		moc_input.o \
		moc_paramsselector.o \
		moc_searcher.o \
		moc_whitesearcher.o \
		moc_whitetable.o \
		moc_settingsdialog.o \
		moc_whiteadddialog.o \
		moc_headercomboboxdelegate.o \
		moc_customtabwidget.o \
		moc_authorisewindow.o \
		moc_greyadddialog.o \
		moc_whitepriceseditor.o \
		moc_changepricedatedialog.o \
		moc_addyeardiscount.o \
		moc_yearsdiscountsdialog.o \
		qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		sql.pro
QMAKE_TARGET  = sql
DESTDIR       = 
TARGET        = sql

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_whiteadddialog.h ui_authorisewindow.h ui_greyadddialog.h ui_whitepriceseditor.h ui_changepricedatedialog.h ui_addyeardiscount.h ui_yearsdiscountsdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sql.pro  /usr/share/qt4/mkspecs/linux-g++-32/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtSql.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile sql.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtSql.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile sql.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/sql1.0.0 || $(MKDIR) .tmp/sql1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sql1.0.0/ && $(COPY_FILE) --parents basetable.h constants.h customcombobox.h detailcard.h helpers.h mainwindow.h mytablemodel.h switcher.h searcher/catalog.h searcher/filters.h searcher/greysearcher.h searcher/greytable.h searcher/input.h searcher/paramsselector.h searcher/searcher.h searcher/whitesearcher.h searcher/whitetable.h settingsdialog.h searcher/whiteadddialog.h headercomboboxdelegate.h customtabwidget.h authorisewindow.h searcher/greyadddialog.h searcher/whitepriceseditor.h changepricedatedialog.h addyeardiscount.h yearsdiscountsdialog.h .tmp/sql1.0.0/ && $(COPY_FILE) --parents images.qrc .tmp/sql1.0.0/ && $(COPY_FILE) --parents basetable.cpp constants.cpp customcombobox.cpp detailcard.cpp helpers.cpp main.cpp mainwindow.cpp mytablemodel.cpp switcher.cpp searcher/catalog.cpp searcher/filters.cpp searcher/greysearcher.cpp searcher/greytable.cpp searcher/input.cpp searcher/paramsselector.cpp searcher/searcher.cpp searcher/whitesearcher.cpp searcher/whitetable.cpp settingsdialog.cpp searcher/whiteadddialog.cpp headercomboboxdelegate.cpp customtabwidget.cpp authorisewindow.cpp searcher/greyadddialog.cpp searcher/whitepriceseditor.cpp changepricedatedialog.cpp addyeardiscount.cpp yearsdiscountsdialog.cpp .tmp/sql1.0.0/ && $(COPY_FILE) --parents searcher/whiteadddialog.ui authorisewindow.ui searcher/greyadddialog.ui searcher/whitepriceseditor.ui changepricedatedialog.ui addyeardiscount.ui yearsdiscountsdialog.ui .tmp/sql1.0.0/ && (cd `dirname .tmp/sql1.0.0` && $(TAR) sql1.0.0.tar sql1.0.0 && $(COMPRESS) sql1.0.0.tar) && $(MOVE) `dirname .tmp/sql1.0.0`/sql1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sql1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_basetable.cpp moc_customcombobox.cpp moc_detailcard.cpp moc_mainwindow.cpp moc_mytablemodel.cpp moc_switcher.cpp moc_catalog.cpp moc_greysearcher.cpp moc_greytable.cpp moc_input.cpp moc_paramsselector.cpp moc_searcher.cpp moc_whitesearcher.cpp moc_whitetable.cpp moc_settingsdialog.cpp moc_whiteadddialog.cpp moc_headercomboboxdelegate.cpp moc_customtabwidget.cpp moc_authorisewindow.cpp moc_greyadddialog.cpp moc_whitepriceseditor.cpp moc_changepricedatedialog.cpp moc_addyeardiscount.cpp moc_yearsdiscountsdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_basetable.cpp moc_customcombobox.cpp moc_detailcard.cpp moc_mainwindow.cpp moc_mytablemodel.cpp moc_switcher.cpp moc_catalog.cpp moc_greysearcher.cpp moc_greytable.cpp moc_input.cpp moc_paramsselector.cpp moc_searcher.cpp moc_whitesearcher.cpp moc_whitetable.cpp moc_settingsdialog.cpp moc_whiteadddialog.cpp moc_headercomboboxdelegate.cpp moc_customtabwidget.cpp moc_authorisewindow.cpp moc_greyadddialog.cpp moc_whitepriceseditor.cpp moc_changepricedatedialog.cpp moc_addyeardiscount.cpp moc_yearsdiscountsdialog.cpp
moc_basetable.cpp: helpers.h \
		constants.h \
		switcher.h \
		basetable.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) basetable.h -o moc_basetable.cpp

moc_customcombobox.cpp: constants.h \
		helpers.h \
		customcombobox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) customcombobox.h -o moc_customcombobox.cpp

moc_detailcard.cpp: helpers.h \
		constants.h \
		mytablemodel.h \
		detailcard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) detailcard.h -o moc_detailcard.cpp

moc_mainwindow.cpp: searcher/searcher.h \
		searcher/filters.h \
		helpers.h \
		constants.h \
		searcher/whitesearcher.h \
		searcher/whitetable.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/greysearcher.h \
		searcher/greytable.h \
		settingsdialog.h \
		customtabwidget.h \
		changepricedatedialog.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_mytablemodel.cpp: constants.h \
		mytablemodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mytablemodel.h -o moc_mytablemodel.cpp

moc_switcher.cpp: constants.h \
		switcher.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) switcher.h -o moc_switcher.cpp

moc_catalog.cpp: helpers.h \
		constants.h \
		searcher/catalog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/catalog.h -o moc_catalog.cpp

moc_greysearcher.cpp: searcher/greytable.h \
		basetable.h \
		helpers.h \
		constants.h \
		switcher.h \
		mytablemodel.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		searcher/filters.h \
		searcher/greysearcher.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/greysearcher.h -o moc_greysearcher.cpp

moc_greytable.cpp: basetable.h \
		helpers.h \
		constants.h \
		switcher.h \
		mytablemodel.h \
		searcher/greytable.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/greytable.h -o moc_greytable.cpp

moc_input.cpp: constants.h \
		helpers.h \
		searcher/input.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/input.h -o moc_input.cpp

moc_paramsselector.cpp: constants.h \
		helpers.h \
		customcombobox.h \
		searcher/paramsselector.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/paramsselector.h -o moc_paramsselector.cpp

moc_searcher.cpp: searcher/filters.h \
		helpers.h \
		constants.h \
		searcher/whitesearcher.h \
		searcher/whitetable.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/greysearcher.h \
		searcher/greytable.h \
		searcher/searcher.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/searcher.h -o moc_searcher.cpp

moc_whitesearcher.cpp: searcher/whitetable.h \
		helpers.h \
		constants.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		searcher/filters.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/whitesearcher.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/whitesearcher.h -o moc_whitesearcher.cpp

moc_whitetable.cpp: helpers.h \
		constants.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/whitetable.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/whitetable.h -o moc_whitetable.cpp

moc_settingsdialog.cpp: constants.h \
		helpers.h \
		settingsdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settingsdialog.h -o moc_settingsdialog.cpp

moc_whiteadddialog.cpp: customcombobox.h \
		constants.h \
		helpers.h \
		headercomboboxdelegate.h \
		searcher/whiteadddialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/whiteadddialog.h -o moc_whiteadddialog.cpp

moc_headercomboboxdelegate.cpp: headercomboboxdelegate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headercomboboxdelegate.h -o moc_headercomboboxdelegate.cpp

moc_customtabwidget.cpp: searcher/searcher.h \
		searcher/filters.h \
		helpers.h \
		constants.h \
		searcher/whitesearcher.h \
		searcher/whitetable.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/greysearcher.h \
		searcher/greytable.h \
		customtabwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) customtabwidget.h -o moc_customtabwidget.cpp

moc_authorisewindow.cpp: constants.h \
		helpers.h \
		mainwindow.h \
		searcher/searcher.h \
		searcher/filters.h \
		searcher/whitesearcher.h \
		searcher/whitetable.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/greysearcher.h \
		searcher/greytable.h \
		settingsdialog.h \
		customtabwidget.h \
		changepricedatedialog.h \
		authorisewindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) authorisewindow.h -o moc_authorisewindow.cpp

moc_greyadddialog.cpp: searcher/greyadddialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/greyadddialog.h -o moc_greyadddialog.cpp

moc_whitepriceseditor.cpp: constants.h \
		helpers.h \
		searcher/whitepriceseditor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searcher/whitepriceseditor.h -o moc_whitepriceseditor.cpp

moc_changepricedatedialog.cpp: helpers.h \
		constants.h \
		changepricedatedialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) changepricedatedialog.h -o moc_changepricedatedialog.cpp

moc_addyeardiscount.cpp: addyeardiscount.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) addyeardiscount.h -o moc_addyeardiscount.cpp

moc_yearsdiscountsdialog.cpp: yearsdiscountsdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) yearsdiscountsdialog.h -o moc_yearsdiscountsdialog.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/first.png \
		images/last.png \
		images/prev.png \
		images/back.png \
		images/camera.png \
		images/reset.png \
		images/next.png \
		images/discount.png \
		images/new.png \
		images/edit.png \
		images/prices.png \
		images/photo.jpg \
		images/delete.png \
		images/settings.png
	/usr/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_whiteadddialog.h ui_authorisewindow.h ui_greyadddialog.h ui_whitepriceseditor.h ui_changepricedatedialog.h ui_addyeardiscount.h ui_yearsdiscountsdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_whiteadddialog.h ui_authorisewindow.h ui_greyadddialog.h ui_whitepriceseditor.h ui_changepricedatedialog.h ui_addyeardiscount.h ui_yearsdiscountsdialog.h
ui_whiteadddialog.h: searcher/whiteadddialog.ui \
		customcombobox.h \
		constants.h \
		helpers.h
	/usr/bin/uic-qt4 searcher/whiteadddialog.ui -o ui_whiteadddialog.h

ui_authorisewindow.h: authorisewindow.ui
	/usr/bin/uic-qt4 authorisewindow.ui -o ui_authorisewindow.h

ui_greyadddialog.h: searcher/greyadddialog.ui
	/usr/bin/uic-qt4 searcher/greyadddialog.ui -o ui_greyadddialog.h

ui_whitepriceseditor.h: searcher/whitepriceseditor.ui
	/usr/bin/uic-qt4 searcher/whitepriceseditor.ui -o ui_whitepriceseditor.h

ui_changepricedatedialog.h: changepricedatedialog.ui
	/usr/bin/uic-qt4 changepricedatedialog.ui -o ui_changepricedatedialog.h

ui_addyeardiscount.h: addyeardiscount.ui
	/usr/bin/uic-qt4 addyeardiscount.ui -o ui_addyeardiscount.h

ui_yearsdiscountsdialog.h: yearsdiscountsdialog.ui
	/usr/bin/uic-qt4 yearsdiscountsdialog.ui -o ui_yearsdiscountsdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

basetable.o: basetable.cpp basetable.h \
		helpers.h \
		constants.h \
		switcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basetable.o basetable.cpp

constants.o: constants.cpp constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constants.o constants.cpp

customcombobox.o: customcombobox.cpp customcombobox.h \
		constants.h \
		helpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customcombobox.o customcombobox.cpp

detailcard.o: detailcard.cpp detailcard.h \
		helpers.h \
		constants.h \
		mytablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detailcard.o detailcard.cpp

helpers.o: helpers.cpp helpers.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpers.o helpers.cpp

main.o: main.cpp helpers.h \
		constants.h \
		mainwindow.h \
		searcher/searcher.h \
		searcher/filters.h \
		searcher/whitesearcher.h \
		searcher/whitetable.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/greysearcher.h \
		searcher/greytable.h \
		settingsdialog.h \
		customtabwidget.h \
		changepricedatedialog.h \
		authorisewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		searcher/searcher.h \
		searcher/filters.h \
		helpers.h \
		constants.h \
		searcher/whitesearcher.h \
		searcher/whitetable.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/greysearcher.h \
		searcher/greytable.h \
		settingsdialog.h \
		customtabwidget.h \
		changepricedatedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mytablemodel.o: mytablemodel.cpp mytablemodel.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mytablemodel.o mytablemodel.cpp

switcher.o: switcher.cpp switcher.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o switcher.o switcher.cpp

catalog.o: searcher/catalog.cpp searcher/catalog.h \
		helpers.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o catalog.o searcher/catalog.cpp

filters.o: searcher/filters.cpp searcher/filters.h \
		helpers.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filters.o searcher/filters.cpp

greysearcher.o: searcher/greysearcher.cpp searcher/greysearcher.h \
		searcher/greytable.h \
		basetable.h \
		helpers.h \
		constants.h \
		switcher.h \
		mytablemodel.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		searcher/filters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o greysearcher.o searcher/greysearcher.cpp

greytable.o: searcher/greytable.cpp searcher/greytable.h \
		basetable.h \
		helpers.h \
		constants.h \
		switcher.h \
		mytablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o greytable.o searcher/greytable.cpp

input.o: searcher/input.cpp searcher/input.h \
		constants.h \
		helpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o input.o searcher/input.cpp

paramsselector.o: searcher/paramsselector.cpp searcher/paramsselector.h \
		constants.h \
		helpers.h \
		customcombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paramsselector.o searcher/paramsselector.cpp

searcher.o: searcher/searcher.cpp searcher/searcher.h \
		searcher/filters.h \
		helpers.h \
		constants.h \
		searcher/whitesearcher.h \
		searcher/whitetable.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/greysearcher.h \
		searcher/greytable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searcher.o searcher/searcher.cpp

whitesearcher.o: searcher/whitesearcher.cpp searcher/whitesearcher.h \
		searcher/whitetable.h \
		helpers.h \
		constants.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		searcher/filters.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o whitesearcher.o searcher/whitesearcher.cpp

whitetable.o: searcher/whitetable.cpp searcher/whitetable.h \
		helpers.h \
		constants.h \
		mytablemodel.h \
		basetable.h \
		switcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o whitetable.o searcher/whitetable.cpp

settingsdialog.o: settingsdialog.cpp settingsdialog.h \
		constants.h \
		helpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsdialog.o settingsdialog.cpp

whiteadddialog.o: searcher/whiteadddialog.cpp searcher/whiteadddialog.h \
		customcombobox.h \
		constants.h \
		helpers.h \
		headercomboboxdelegate.h \
		ui_whiteadddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o whiteadddialog.o searcher/whiteadddialog.cpp

headercomboboxdelegate.o: headercomboboxdelegate.cpp headercomboboxdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headercomboboxdelegate.o headercomboboxdelegate.cpp

customtabwidget.o: customtabwidget.cpp customtabwidget.h \
		searcher/searcher.h \
		searcher/filters.h \
		helpers.h \
		constants.h \
		searcher/whitesearcher.h \
		searcher/whitetable.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/greysearcher.h \
		searcher/greytable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customtabwidget.o customtabwidget.cpp

authorisewindow.o: authorisewindow.cpp authorisewindow.h \
		constants.h \
		helpers.h \
		mainwindow.h \
		searcher/searcher.h \
		searcher/filters.h \
		searcher/whitesearcher.h \
		searcher/whitetable.h \
		mytablemodel.h \
		basetable.h \
		switcher.h \
		searcher/catalog.h \
		searcher/input.h \
		searcher/paramsselector.h \
		customcombobox.h \
		detailcard.h \
		searcher/whiteadddialog.h \
		headercomboboxdelegate.h \
		searcher/whitepriceseditor.h \
		searcher/greysearcher.h \
		searcher/greytable.h \
		settingsdialog.h \
		customtabwidget.h \
		changepricedatedialog.h \
		ui_authorisewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o authorisewindow.o authorisewindow.cpp

greyadddialog.o: searcher/greyadddialog.cpp searcher/greyadddialog.h \
		ui_greyadddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o greyadddialog.o searcher/greyadddialog.cpp

whitepriceseditor.o: searcher/whitepriceseditor.cpp searcher/whitepriceseditor.h \
		constants.h \
		helpers.h \
		ui_whitepriceseditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o whitepriceseditor.o searcher/whitepriceseditor.cpp

changepricedatedialog.o: changepricedatedialog.cpp changepricedatedialog.h \
		helpers.h \
		constants.h \
		ui_changepricedatedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changepricedatedialog.o changepricedatedialog.cpp

addyeardiscount.o: addyeardiscount.cpp addyeardiscount.h \
		ui_addyeardiscount.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addyeardiscount.o addyeardiscount.cpp

yearsdiscountsdialog.o: yearsdiscountsdialog.cpp yearsdiscountsdialog.h \
		ui_yearsdiscountsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yearsdiscountsdialog.o yearsdiscountsdialog.cpp

moc_basetable.o: moc_basetable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basetable.o moc_basetable.cpp

moc_customcombobox.o: moc_customcombobox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customcombobox.o moc_customcombobox.cpp

moc_detailcard.o: moc_detailcard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_detailcard.o moc_detailcard.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mytablemodel.o: moc_mytablemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mytablemodel.o moc_mytablemodel.cpp

moc_switcher.o: moc_switcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_switcher.o moc_switcher.cpp

moc_catalog.o: moc_catalog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_catalog.o moc_catalog.cpp

moc_greysearcher.o: moc_greysearcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_greysearcher.o moc_greysearcher.cpp

moc_greytable.o: moc_greytable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_greytable.o moc_greytable.cpp

moc_input.o: moc_input.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_input.o moc_input.cpp

moc_paramsselector.o: moc_paramsselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_paramsselector.o moc_paramsselector.cpp

moc_searcher.o: moc_searcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searcher.o moc_searcher.cpp

moc_whitesearcher.o: moc_whitesearcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_whitesearcher.o moc_whitesearcher.cpp

moc_whitetable.o: moc_whitetable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_whitetable.o moc_whitetable.cpp

moc_settingsdialog.o: moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsdialog.o moc_settingsdialog.cpp

moc_whiteadddialog.o: moc_whiteadddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_whiteadddialog.o moc_whiteadddialog.cpp

moc_headercomboboxdelegate.o: moc_headercomboboxdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headercomboboxdelegate.o moc_headercomboboxdelegate.cpp

moc_customtabwidget.o: moc_customtabwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customtabwidget.o moc_customtabwidget.cpp

moc_authorisewindow.o: moc_authorisewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_authorisewindow.o moc_authorisewindow.cpp

moc_greyadddialog.o: moc_greyadddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_greyadddialog.o moc_greyadddialog.cpp

moc_whitepriceseditor.o: moc_whitepriceseditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_whitepriceseditor.o moc_whitepriceseditor.cpp

moc_changepricedatedialog.o: moc_changepricedatedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changepricedatedialog.o moc_changepricedatedialog.cpp

moc_addyeardiscount.o: moc_addyeardiscount.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addyeardiscount.o moc_addyeardiscount.cpp

moc_yearsdiscountsdialog.o: moc_yearsdiscountsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_yearsdiscountsdialog.o moc_yearsdiscountsdialog.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

